# Generated by Django 4.2.30 on 2026-09-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_at', models.DateTimeField(auto_now_add=True, verbose_name='Собран')),
                ('document_count', models.PositiveIntegerField(verbose_name='Документов')),
                ('chunk_count', models.PositiveIntegerField(verbose_name='Фрагментов')),
                ('embed_model', models.CharField(max_length=128, verbose_name='Модель эмбеддингов')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Сборка индекса',
                'verbose_name_plural': 'Сборки индекса',
                'ordering': ['-built_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/', verbose_name='Файл')),
                ('content', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в индексе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ знаний',
                'verbose_name_plural': 'Документы знаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
