"""create qa_cache with correct primary key

Revision ID: 0356ce8042d8
Revises: 
Create Date: 2025-06-02 17:08:18.655569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0356ce8042d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_cache_id'), 'qa_cache', ['id'], unique=False)
    op.create_index(op.f('ix_qa_cache_question'), 'qa_cache', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_cache_question'), table_name='qa_cache')
    op.drop_index(op.f('ix_qa_cache_id'), table_name='qa_cache')
    op.drop_table('qa_cache')
    # ### end Alembic commands ###
