# Generated by Django 4.2.30 on 2026-09-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Кэш ответа',
                'verbose_name_plural': 'Кэш ответов',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('human', 'Пользователь'), ('ai', 'Бот')], max_length=16, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='qa.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение диалога',
                'verbose_name_plural': 'Сообщения диалога',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_ru', models.TextField(blank=True, verbose_name='Вопрос (ru)')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('language', models.CharField(default='ru', max_length=8, verbose_name='Язык')),
                ('source', models.CharField(choices=[('cache', 'Кэш'), ('rag', 'RAG'), ('unanswered', 'Без ответа')], default='rag', max_length=16, verbose_name='Источник')),
                ('is_unanswered', models.BooleanField(default=False, verbose_name='Без ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Задан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='qa.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='qa_question_created_149b3d_idx'), models.Index(fields=['is_unanswered'], name='qa_question_is_unan_f8e1fd_idx'), models.Index(fields=['language'], name='qa_question_languag_615ef3_idx')],
            },
        ),
    ]
